# Generated by Django 2.2 on 2021-03-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='confirmed_password',
        ),
    ]
